# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sateesh K Peddoju, Ph. D
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  drpskfec

# Build settings
markdown: kramdown
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: drpskfec/drpskfec.github.io

defaults:
  # _posts
  - scope:
      path: ""
      type: home
    values:
      author_profile: true

author:
  name   : "Sateesh K Peddoju, Ph. D"
  avatar : "images/profile.jpg"
  bio    : "SMACM, SMIEEE,  <br> MOPF, MCSI, MIETE, MISTE<br> <br> Assistant Professor, "<a href=\"https://www.iitr.ac.in/departments/CSE/pages/index.html\">Department of CSE</a><br>&nbsp;&nbsp;&emsp;<a href=\"https://www.iitr.ac.in\">IIT Roorkee</a>""
        #uri    : "www.peddoju.com"
  location : 
  linkedin: peddoju
  facebook: prof.sateesh
  googlescholar: https://scholar.google.co.in/citations?user=Nx2gTocAAAAJ
  phone: (+91) 1332-28-5647
  dblp: http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_Kumar
  dblp1: http://dblp.uni-trier.de/pers/hd/p/Peddoju:Sateesh_K=
  dblp2: http://dblp2.uni-trier.de/pers/hd/k/Kumar:P=_Sateesh

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - google_scholar.rb
  - generate_pubs.rb
  - tex2html.rb
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
